/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as EventsCreateIndexRouteImport } from './routes/events/create/index'
import { Route as EventsEventIdEditIndexRouteImport } from './routes/events/$eventId/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateIndexRoute = EventsCreateIndexRouteImport.update({
  id: '/events/create/',
  path: '/events/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditIndexRoute = EventsEventIdEditIndexRouteImport.update({
  id: '/events/$eventId/edit/',
  path: '/events/$eventId/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/events/create/': typeof EventsCreateIndexRoute
  '/events/$eventId/edit/': typeof EventsEventIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/events/create': typeof EventsCreateIndexRoute
  '/events/$eventId/edit': typeof EventsEventIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/events/create/': typeof EventsCreateIndexRoute
  '/events/$eventId/edit/': typeof EventsEventIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/events/$eventId/' | '/events/create/' | '/events/$eventId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events/$eventId' | '/events/create' | '/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/events/$eventId/'
    | '/events/create/'
    | '/events/$eventId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  EventsCreateIndexRoute: typeof EventsCreateIndexRoute
  EventsEventIdEditIndexRoute: typeof EventsEventIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create/': {
      id: '/events/create/'
      path: '/events/create'
      fullPath: '/events/create/'
      preLoaderRoute: typeof EventsCreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/edit/': {
      id: '/events/$eventId/edit/'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit/'
      preLoaderRoute: typeof EventsEventIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  EventsCreateIndexRoute: EventsCreateIndexRoute,
  EventsEventIdEditIndexRoute: EventsEventIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
